repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.4.2
    hooks:
      - id: sqlfluff-lint
        # We want to reuse existing python virtual environment to run sqlfluff
        language: system